wandb_version: 1

epochs:
  desc: null
  value: 5
classes:
  desc: null
  value: 10
kernels:
  desc: null
  value:
  - 16
  - 32
batch_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.005
dataset:
  desc: null
  value: MNIST
architecture:
  desc: null
  value: CNN
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689084712.15432
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.6
      5: 0.15.5
      8:
      - 1
      - 5
